### ISSUE TITLE
Create a redirect menu item for labs

### ISSUE THREAD

**Issue by nealbastek** [okfn/website#102]
Needs to be a sub menu item under 'get involved'

**Comment by morchickit** [comment]
@danfowler - can you help here?

**Comment by pwalsh** [comment]
Hold on that for the moment please.

**Comment by k-nut** [comment]
@pwalsh should I create a new redirectview for this now?

**Comment by pwalsh** [comment]
@k-nut yes, to http://okfnlabs.org

**Comment by k-nut** [comment]
Where is it that we want to include this? I cannot find a `get involved` menu anymore. It looks like that was only in the old website?!

**Comment by morchickit** [comment]
@danfowler and @pwalsh can we close it and re-open and issue when we have better knowledge on the labs website?

**Comment by pwalsh** [comment]
ok
