### ISSUE TITLE
Add oembed support to CMS

### ISSUE THREAD

**Issue by nickstenning** [okfn/website#109]
So that people can safely embed YouTube videos, Flickr galleries, etc.

See: https://github.com/divio/djangocms-oembed

**Comment by k-nut** [comment]
It seems like the [aldryn-video](https://github.com/aldryn/aldryn-video) was more recently updated and might have better support. I might try including this one.

**Comment by k-nut** [comment]
Nevermind. The aldryn one actually is not published on PyPi..
