### ISSUE TITLE
add 'language' field to network app

### ISSUE THREAD

**Issue by nealbastek** [okfn/website#135]
I think these cover most of our groups:

English
Spanish
French
German
Italian
Russian
Chinese
Japanese
Portuguese
Finnish
Dutch
Bangla
Other:
????

If possible, I'd like to be able to edit this list easily ala the project types list.

**Comment by pwalsh** [comment]
@nealbastek 

So we want a language entity, and people + network groups can have one or many languages?

**Comment by morchickit** [comment]
yes. I am closing this. It can be confusing with translations.
