### ISSUE TITLE
Fix whitespace around cms_link plugin instances

### ISSUE THREAD

**Issue by nickstenning** [okfn/website#176]
There shouldn't be mandatory whitespace before/after cms_link plugin instances. It makes links at the end of sentences look [ugly](#likethis) .

**Comment by pwalsh** [comment]
For investigation.

**Comment by k-nut** [comment]
I cannot reproduce the problem. Here I created a new link with a period directly at the end. Or am I misunderstanding this issue?
<img width="346" alt="screen shot 2016-06-13 at 13 44 11" src="https://cloud.githubusercontent.com/assets/1096357/16006360/f7fe4a48-316c-11e6-8a4d-10e4dc7f8909.png">

**Comment by k-nut** [comment]
@pwalsh @morchickit ☝️ 👀

**Comment by pwalsh** [comment]
FIXED.
