### ISSUE TITLE
add section at bottom of front page with info about open

### ISSUE THREAD

**Issue by LaurieJ** [okfn/website#190]
We had this in an earlier draft but it was cut. 

Suggest we add a block at the bottom below key themes to say:

<i>Open</i> means freely shared for anyone, anywhere, to use for any purpose

We believe open knowledge enables people to better understand our world and tackle global and local challenges, combat injustice and inequality, expose inefficiency, and hold governments and companies to account. 

Open Knowledge is a worldwide community of people passionate about openness, using advocacy, technology and training to unlock information and enable people to work with it to create and share knowledge.

**Comment by pwalsh** [comment]
@smth yes, no, maybe?

**Comment by smth** [comment]
I can incorporate this into the "design", yes.

**Comment by pwalsh** [comment]
Closing in favor of the general home redesign that @smth is doing in #276
