### ISSUE TITLE
Press page: Redesign

### ISSUE THREAD

**Issue by nealbastek** [okfn/website#211]
Add social media icons in sidebar

**Comment by morchickit** [comment]
Move Media Inquiries to the main page and out of sidebar

**Comment by smth** [comment]
It seems to me that pretty much everything on this page is out dated. If the "recent" press releases and press mentions are as lacking in updates as they appear, we should think about if and how these can be kept up to date in the future (i.e can we pull blog posts with appropriate tags?), and whether we keep them on the page.

**Comment by morchickit** [comment]
Currently no one is even collect these mentions.
I guess I can do some slack search and add new ones, the question is if they will be sustainable... 
Maybe we can mechanise it while using google news search?

**Comment by morchickit** [comment]
https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#tbm=nws&q=%22open+knowledge+international%22
