### ISSUE TITLE
Properly configure Google Webmaster Tools/Search Console

### ISSUE THREAD

**Issue by nealbastek** [okfn/website#221]
Setting this up as a reminder for an ongoing task. 

Leave a comment on this issue when you run http://brokenlinkcheck.com and report on your activities.

**Comment by morchickit** [comment]
@pwalsh - thoughts?

**Comment by pwalsh** [comment]
@morchickit I changed the title. There is a better way, and it is something we need for all our sites. I'll show you when we finish the bulk of the work.

**Comment by morchickit** [comment]
@pwalsh Should we address this soon or should I move it to backlog?

**Comment by pwalsh** [comment]
I should do it soon.....
