### ISSUE TITLE
Link to Services Website

### ISSUE THREAD

**Issue by smth** [okfn/website#224]
Link(s) to 'Services' should now point to http://services.okfn.org/

**Comment by morchickit** [comment]
@pwalsh what is the status with this and the Viderum site? Can I close this issue?

**Comment by morchickit** [comment]
@pwalsh See the above comment.

**Comment by pwalsh** [comment]
@morchickit assign it to me for the new current milestone.

**Comment by smth** [comment]
This issue is redundant now, right? There isn't currently a "services" link, as far as I can see.
