### ISSUE TITLE
search on okfn.org not indexing all pages

### ISSUE THREAD

**Issue by svanderwaal** [okfn/website#235]
Search on okfn.org is broken or at least incomplete.
Eg. both 'Peter' and 'Cambrigde' yield no results.
'Peter' is on https://okfn.org/about/advisory-council/
'Cambridge' is on https://okfn.org/about/
'mission' yields results but not the page that describes our mission, https://okfn.org/about/

Also, next to the search button is 'fl' instead of an arrow or something that clearly describes 'submit my search query'.

**Comment by nigelbabu** [comment]
I'm going to leave this issue about search indexing and create a new issue for the 'fl' button. That seems something odd with font awesome.

**Comment by nigelbabu** [comment]
This is slightly better now. Searching for 'Peter' does yield the right results, but searching for 'mission' doesn't yet.

**Comment by pwalsh** [comment]
post save hooks.

**Comment by k-nut** [comment]
I can confirm that this still happens on the live blog. When I run the search locally against a dump of the (staging) database I get a lot more results...

**Comment by k-nut** [comment]
I can also confirm that there seem to not be any results for the `/about` page.

**Comment by pwalsh** [comment]
@k-nut look into Haystack and see about how creating search documents for the index works. I guess that when this was originally done, it was just not done comprehensively (missing pages), and was not configured properly for production (lack of results on deployed site).
