### ISSUE TITLE
Events page needs content update

### ISSUE THREAD

**Issue by nigelbabu** [okfn/website#239]
The events page talks about okfestival in Berlin as upcoming. We need to update that as past and add details of upcoming ones as well.

**Comment by harry-wood** [comment]
Also the two calendar links on the left are ...a bit lame.  1st one is a link to calendar containing... no events.  I found another calendar on here which is less empty: http://okfnlabs.org/events/   .....maybe merge and have one calendar? The 2nd one is a link to wiki heading which no longer exists (should be http://wiki.okfn.org/Events  ?  Anyone updating anything there?

**Comment by morchickit** [comment]
Moving events guide to handbook. Will open this page when the new OKFest is on
