### ISSUE TITLE
Re-design / omit the sidebar

### ISSUE THREAD

**Issue by morchickit** [okfn/website#253]
Currently the sidebar is used on the website to refer to new content / different parts of the website. I do feel like it actually vert hidden and looks like a duplicate to the tool bar. @smth - can you have a look at the current site situation and give your opinion on what should we do with it?

**Comment by smth** [comment]
Bluntly, we need to spend some time on this site.

Addressing the issue of the two menus specifically, a quick win could be to duplicate the side bar menu contents in some form of drop-down from the main navigation, as this is a conventional location for sub-pages.

**Comment by morchickit** [comment]
OK, I created #254 254
The side bar is because we don't have a drop down currently.

**Comment by pwalsh** [comment]
This is covered by #254 and the various page/section redesigns.
