### ISSUE TITLE
Main navigation: Redesign

### ISSUE THREAD

**Issue by morchickit** [okfn/website#254]
The current navigation is impossible.

**Comment by smth** [comment]
Do you think something like this would address the issues you have found @morchickit ?
![okfn_01_menu_01](https://cloud.githubusercontent.com/assets/1375708/15246364/349fb47c-1904-11e6-93ee-538accecc3a2.jpg)

**Comment by morchickit** [comment]
Yes! Definitely!

**Comment by pwalsh** [comment]
but needs a mobile treatment too.

**Comment by smth** [comment]
Mobile should work in a similar way, utilising the slide mechanism used in the [Open Data Handbook](http://opendatahandbook.org/).
![okfn_01_small_menu_01](https://cloud.githubusercontent.com/assets/1375708/15283608/c18e28aa-1b43-11e6-8403-28123218c754.jpg)

**Comment by pwalsh** [comment]
@smth ok.
