### ISSUE TITLE
Add Join the our forum on homepage

### ISSUE THREAD

**Issue by morchickit** [okfn/website#256]
Currently we only give option to people to join our mailing list.

**Comment by smth** [comment]
Perhaps the logical place for this is in the top menu, along with the blog and social networks?

**Comment by morchickit** [comment]
Then we should move the newsletter to there as well

**Comment by smth** [comment]
While I'm open to moving the newsletter sign up, it is slightly different, in that it doesn't have (or need) a page. So unless we want to create a page for it, putting it in the navigation doesn't really work.

It's also different in its passivity. I think the footer might be a better location, if we no longer want to give it such a dominant position.

**Comment by morchickit** [comment]
We had one newsletter in the past year, and until we will have a proper comms person, I feel like giving it such a prominent place is an issue. I prefer to direct people to the discuss, where more of our efforts now, then the newsletter.

**Comment by smth** [comment]
That makes sense. So let's move the newsletter sign-up and give its spot to a message about the forum.
![okfn_01_home_01](https://cloud.githubusercontent.com/assets/1375708/15292809/d7947d32-1b7c-11e6-911a-0ec0fd455408.jpg)

**Comment by morchickit** [comment]
<3 !!!!

**Comment by pwalsh** [comment]
Does not need a distinct issue. Belong sin #276
