### ISSUE TITLE
Projects page: Redesign

### ISSUE THREAD

**Issue by morchickit** [okfn/website#257]
https://okfn.org/projects/ - 

Due to lack of personnel I would like to do the following tweaks to this page:
- [x] Remove the filter by in the top right-hand side
- [x] Divide the page into two sections - Current projects and Past projects
- [ ] Keep the one-liners, design them so they won't cut in the middle of the sentence (I am guessing that right now it takes a snippet from the project page). 
- [ ] Add an image to each project. 
- [x] Hide individual project pages (for now)
- [x] Link the image and the 'find out more' box to the project website. 

Current projects:
- Open Trials
- Open Spending
- CKAN
- Open Data Handbook
- Open Data Index
- Open Data Census
- Open Data for Development
- Open GLAM
- The Route to PA
- School of Data
- The Open Definition
- Public Domain Review
- FutureTDM

Past projects:
- Stop Secret Contracts Campaign
- Apps for Europe
- D-CENT
- DM2E
- Global Open Data Initiative
- LinkedUp
- LOD2
- Open data and Privacy
- Open Development Toolkit
- Panton Fellowships
- Partnership for Open Data

@svanderwaal - Please let me know what we are missing!

**Comment by morchickit** [comment]
@smth - also any other design comment from you is welcome!

**Comment by smth** [comment]
Sounds good. I wonder whether, instead of "current" and "past", we should align this with our portfolios (planting the trees, growing the trees, harvesting the fruits)? Though I do prefer your less abstracted terminology @morchickit .

**Comment by morchickit** [comment]
It is a good idea @smth - but I think it's going to take time until we will work in portfolios. @svanderwaal - thoughts? 
BTW - we will still need to mentions past projects in that page, even with the new portfolios...

**Comment by morchickit** [comment]
@smth - @nealbastek is going to do the one liners for each project!

**Comment by smth** [comment]
![okfn_02_projects_01](https://cloud.githubusercontent.com/assets/1375708/16049618/4c3c8014-3250-11e6-9cb3-692a3c22a136.jpg)

(I'm suggesting we put "past projects" on a separate page)

**Comment by morchickit** [comment]
+1 for the separate page!
