### ISSUE TITLE
Network page: Redesign

### ISSUE THREAD

**Issue by morchickit** [okfn/website#262]
And make it more appealing for people... (because currently it just look like two lists...)

**Comment by smth** [comment]
Fleshing this out a little:

- This page should do a better job of showing that the Chapters and Local groups are comprised of people.
- Should be more welcoming, exciting in regards to encouraging participation.
- Make better use of the space when listing the Chapters / Groups.
- Explain what Chapters and Local groups are (and hence the difference).
- Add some some info and/or a photo to each Chapter (and group?).

Thoughts @morchickit Anything to add?

**Comment by morchickit** [comment]
See also network guidelines to learn more about the network. https://okfn.org/network/network-guidelines/

Groups has a template page, which is REALLY hard to maintain updated (I am trying for the last year). 
I will say that it will be good to add blog posts that are from the chapters / groups and to link to the forum
