### ISSUE TITLE
Add different groups type

### ISSUE THREAD

**Issue by morchickit** [okfn/website#266]
Currently we have only Chapters and Groups. 

Groups can be at the moment:
Chapter or Group.

Groups should be:
Chapter
Established Group
Incubating Group
Affiliate
Hybernated Group

**Comment by pwalsh** [comment]
@morchickit are we sure we want so many different group types? Also, how is this information exposed to the user interface of the website?

**Comment by morchickit** [comment]
Yes, because we have all these types of groups and it's important information people should know about. I was thinking of having it on a map showing only active groups, and having the Hybernated Group as a hidden group, a status that we only use. 
Do we want to connect this to HubSpot maybe?

**Comment by morchickit** [comment]
@yotammanor can you look at this?

**Comment by yotammanor** [comment]
I can.
But i have some product/design questions @morchickit :

- Are all group types visible on the website?
- Is there any aspect by which group types are different (except for a title that lists them)?
- Is there any Hierarchy among the groups mentioned? (e.g. are "Established Group" and "Incubating Group" a type of a "Local Group", and a "Chapter" is a different type of 'thing'?)
 - If so, should this hierarchy be reflected in how they are displayed in the website?
- What order should the groups appear by (especially if there is no hierarchy among them, but either way)
- You did not mention the currently existing "local group" as a particular type. Is it to be replaced all the others?

**Comment by morchickit** [comment]
- Yes- all of these will be visible on the site.
- type is not different
- No Hierarchy (like, in theory - incubating group becomes Established group becomes chapter, but no need to hierarchy) 
- They should be shown as groups in columns for the time being until the new design will be role out. if there is no group in a column, do not show the column. 
- Local groups should be replaced by Established Group and Incubating Group

**Comment by yotammanor** [comment]
@morchickit a Hibernated group is also visible?

**Comment by morchickit** [comment]
yes, Hibernated group should be visible

**Comment by yotammanor** [comment]
In order to make this change show on the website:

- [ ] deploy
- [ ] edit the network page
- [ ] re-add all text elements
- [ ] add the a `network group flag` plugin for each type to be displayed.

**Comment by morchickit** [comment]
What's the status of this?

**Comment by yotammanor** [comment]
the feature is ready, awaits deployment (and post-deployment Admin changes)

**Comment by yotammanor** [comment]
@morchickit this is now done.
In order to add extra group types, change the type for the relevant groups on the admin, and then edit networks page and add the required extra group types as a new plugin.

**Comment by morchickit** [comment]
Awesome! This is working nicely. Now we just need a new design...  :-)
