### ISSUE TITLE
Changes in Admin interface for easier use

### ISSUE THREAD

**Issue by pwalsh** [okfn/website#267]
# Description

Some of the user flows int he admin have not been designed for normal humans. The admin UI is quite flexible (Django Admin) and we can easily do useful things like nesting model forms and such to make it simpler for content editors.
# Tasks
- TBD

**Comment by morchickit** [comment]
Including hide page (!)

**Comment by pwalsh** [comment]
@morchickit @nealbastek this stays on the backlog until I can get a clear list of user flows that need addressing.

**Comment by morchickit** [comment]
Does that mean you need me to write these user flows?
