### ISSUE TITLE
Remove less as a deployment dependency

### ISSUE THREAD

**Issue by pwalsh** [okfn/website#270]
erm.. not worth the overhead just to compile a few css files. Just commit css directly to the repo.

**Comment by k-nut** [comment]
Just to make sure that I understand this: We want to remove less (or rather SASS as that is used in the new design) as a compile step but still keep using it, correct? So just transpile the css files locally with sass and commit those files

**Comment by pwalsh** [comment]
@k-nut yeah, sure. no need to build css on a production server. you can, of course, do it as part of continuous deployment if you want to look at that.

**Comment by k-nut** [comment]
The new system uses sass not less. I removed the scripts responsible for building the sass. We still build sass on the production machine (as well as install frontend dependencies via bower now). I think it makes sense to do this especially now where things change quite a lot. I might remove the sass step later but I do not think that it is necessary...

**Comment by pwalsh** [comment]
Hey Knut. Let's talk about this in coming days; we really should not build in production. Also, I didn't realize we use bower here, and we probably should shift to npm as with all other recent OKI projects, and much of the front end world in general.

**Comment by morchickit** [comment]
@pwalsh What should I do here? Do we want to proceed with this?

**Comment by pwalsh** [comment]
backlog.

**Comment by smth** [comment]
I have started compiling the SCSS locally, so any any step to do this on the server can be removed in the near future.
