### ISSUE TITLE
Change the tagline!

### ISSUE THREAD

**Issue by samgoeta** [okfn/website#271]
2 years ago, we had several discussions about the new Open Knowledge tagline and nothing has changed since!
http://www.timdavies.org.uk/2014/04/12/data-information-knowledge-and-power-exploring-open-knowledges-new-core-purpose/
https://lists.okfn.org/pipermail/okfn-discuss/2014-May/010329.html
https://lists.okfn.org/pipermail/okfn-discuss/2014-June/010445.html
…
I know there is a reboot of the website going on so let's find something which better reflects the diversity of the community

**Comment by morchickit** [comment]
Is #256 looks better?

**Comment by pwalsh** [comment]
@morchickit @samgoeta I don't see a need to track this as a distinct issue here.

1. In terms of implementation, any changes will come out in #276 
2. If there is need for wider community discussion (on a very old issue), then clearly the [forum](https://discuss.okfn.org) is the best place for that.
