### ISSUE TITLE
plugins not deleting

### ISSUE THREAD

**Issue by nealbastek** [okfn/website#272]
I'm trying to delete plugin 2833 and its child 3265, and plugin 3517 from the left sidebar of this page https://okfn.org/network

when I hit delete from the edit screen I get a confirmation window that has a red 'Yes I'm sure' button, when I click that button, the loading icon spins and spins but nothing happens. 

Can someone fix the bug and/or delete the plugins from the database please and thank you.

**Comment by nealbastek** [comment]
This seems like a browser issue. It's still not working in FF for the Mac, but I got it to work fine on Safari. Not urgent at all.

**Comment by pwalsh** [comment]
This is in our dependencies. Currently opting to close.
