### ISSUE TITLE
Team page: Redesign

### ISSUE THREAD

**Issue by morchickit** [okfn/website#274]

**Comment by smth** [comment]
Mockup for this page:
![profile_01](https://cloud.githubusercontent.com/assets/1375708/15864265/4e7995d8-2cce-11e6-9de3-08736d798d40.jpg)

**Comment by morchickit** [comment]
Yes, Let's add to here to change the design to make it more relatable!

**Comment by morchickit** [comment]
@smth - currently staff is divided to leadership, project delivery, technical, operations and Viderum. 

We should create a different structure - 
Leadership
Office of the CEO (Research, Comms, Community) 
Projects Delivery (i think we should have some order here by projects, currently is all over the place)
Tech 
Operations
