### ISSUE TITLE
Homepage: Redesign

### ISSUE THREAD

**Issue by morchickit** [okfn/website#276]

**Comment by smth** [comment]
A note about content here. Currently the two most highlighted sections on the home page, "A Global Network" and "Open Expertise", link to a [404](https://okfn.org/get-involved/) and a [page that suggests irrelevance](http://services.okfn.org/).

**Comment by morchickit** [comment]
A global network should not cause 404... o_0

**Comment by smth** [comment]
![okfn_02_home_01](https://cloud.githubusercontent.com/assets/1375708/16049493/d4bb390e-324f-11e6-845c-e6af71c24886.jpg)

**Comment by morchickit** [comment]
@smth - one question, the pics of the lower section , the blog snippets, where are the pic from? Sometimes the blog users don't add a pic... (just thinking ahead here)

**Comment by smth** [comment]
Good question @morchickit I wanted to note this somewhere. To achieve what we are trying to here, we need to encourage people to add a profile pic. A bigger assumption here though, is that more people blog under their own name, rather than "Open Knowledge International".

**Comment by smth** [comment]
Perhaps a bigger question is: Where are the news items in the banner coming from?

**Comment by morchickit** [comment]
Ha!
So we have news tag on the blog, so that's not a problem.
Maybe you can get more content from planet.okfn.org? That will very
diverse!
About the blog, we can encourage that for sure.

**Comment by smth** [comment]
That news section will require specifically sized images, and a relatively specific amount of text. So I  some human action might need to be involved.

**Comment by morchickit** [comment]
Since we don't have a comms person, I am not sure the news will change so
often... maybe we need to think if a static alternative?
On 15 Jun 2016 5:56 p.m., "Sam Smith" <notifications@github.com> wrote:

That news section will require specifically sized images, and a relatively
specific amount of text. So I some human action might need to be involved.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/okfn/website/issues/276#issuecomment-226250420>, or mute
the thread
<https://github.com/notifications/unsubscribe/ADHzu6twX3nZmhPsU1huyl5ke4PkZf0fks5qMC7KgaJpZM4Ixxgb>
.

**Comment by smth** [comment]
I agree that is a problem @morchickit but I'm not sure that means we should give up on it. I think everyone would agree it is still something we need do.

If we don't think it's possible to maintain however, that's potentially a big change to the design (I'd need to rethink how we enforce the mission statement in a static way), so we should make a decision on this sooner rather than later.

**Comment by morchickit** [comment]
OK, the section, now call "announcements" or "highlights" should link to pages in the website itself. 
@pwalsh do the website support anchor links?

**Comment by pwalsh** [comment]
@morchickit the website supports what ever we tell it too, so yes :)

**Comment by morchickit** [comment]
question is do i need to open the issue about it or not? :-)

**Comment by pwalsh** [comment]
@morchickit it is hard to say: anchors are a property of the way the HTML is written. As long as @smth and @k-nut add anchors to relevant sections of pages as part of the rest of the work, then we are good.

**Comment by k-nut** [comment]
There also already are anchors on some parts of the code. It is for example possible to link to people in the team page as those are generated from the database. It's probably more difficult to make sure that this works in user supplied content but there probably is a way in the editor to make sure of that.
