### ISSUE TITLE
Network page template bug

### ISSUE THREAD

**Issue by nealbastek** [okfn/website#277]
If you look at https://okfn.org/network/ in the CMS admin right now it appears to have no content in a draft state (unpublished changes), I'm not sure how this happened, but I can't get back to see the content that is showing up on the live (published) site. 

Initially, I couldn't get the ‘In this section’ menu to work on this page  https://okfn.org/network/  It works on the about page, and it works on this child page https://okfn.org/network/network-guidelines/ but it’s gone from /network and in trying to get it back I think I’ve caused a couple other problems.

Here’s what I’ve done:

1. I unpublished /get-involved because the ‘in this section’ menu wasn’t working their either and then moved /network up a level in the content tree so it would be part of the main menu. That didn’t fix the problem.

2. I’ve toggled templates back and forth a couple times  on /network. Nothing worked. I don’t see any setting in the admin that gives me any clue as to how that menu renders.

3. I changed the page title of ‘The Global Network’ page to ‘The Open Knowledge Network’ so it would read better in the main menu. This seems to have erased all the content on the /network page.

4. So, there are unpublished changes on the /network page and I am afraid that if I publish them the content will disappear.

5. The current live public version of the site looks relatively ok. Really the only thing that’s missing is the Working Group directory link in the sidebar of /network.

**Comment by k-nut** [comment]
I discussed with @nealbastek a way to solve this without code by reverting to a previous version of the page with the inline editor. I'm not sure what was broken here but this seems to be the path of the least resistance.

**Comment by pwalsh** [comment]
@k-nut @nealbastek ok, so close and move to done if done.
