### ISSUE TITLE
Team page: Content

### ISSUE THREAD

**Issue by pwalsh** [okfn/website#279]
From @morchickit 

- [ ] Change the structure to the current organigram
- [ ] Add Mark
- [ ] Add John
- [ ] Add Danny
- [ ] Add Oscar
- [ ] Add Franka
- [ ] Add Victoria
- [ ] Add Georgina 

- Remove - 

- [ ] Arturas
- [ ] Sebastian

**Comment by morchickit** [comment]
So, we need to deal with Viderum question. As I see it we have two options - 
1. To include Viderum on our staff page, making clear that they are a different entity as well (but part of the staff) and creating a link to it from the Viderum site to our staff page.
2. To create a staff page on the Viderum site and create links between the two staff pages (something like - "see our colleagues at Viderum") 

I am waiting to Pavel and Mark to decide on this. 
@smth and @pwalsh - FYI
