### ISSUE TITLE
Projects page: Content

### ISSUE THREAD

**Issue by pwalsh** [okfn/website#281]
Any additional content required to support #262

On liner on each - 
- [x] OpenSpending
- [x] PASTEUR4OA
- [x] Open Trials
- [ ] CKAN
- [x] Frictionless Data
- [x] School of Data
- [ ] Open Data for TaxJustice
- [x] OD4D 
- [x] Global Open Data Index
- [x] African Open Data Collaboration Fund
- [x] Route-To-PA
- [x] FutureTDM
- [x] Open Budgets EU
- [ ] Open Data Handbook

**Comment by jobarratt** [comment]
@morchickit as i don't quite know how this is going to be used, there is a shorter and longer version (in brackets)

Frictionless Data is about removing the friction in working with data (though the creation of tools, standards, and best practices for publishing data using the Data Package standard, a containerization format for any kind of data.)

**Comment by morchickit** [comment]
@jobarratt - this is perfect, thank you!

**Comment by cecilaki** [comment]
@morchickit 

**OpenSpending** is a centralized platform on the topic of public financial information, including an global database of budgets and spending data, a community of contributors and users exposing cases, and a set of open resources and tools providing technical, fiscal, and political understanding necessary to work with financial data.

**Comment by liekeploeger** [comment]
The **FutureTDM project** seeks to improve uptake of text and data mining (TDM) in the EU by actively engaging with stakeholders such as researchers, developers, publishers and SMEs.

**Comment by KateRogers** [comment]
The Global Open Data Index is a civil society collaborative effort to track the state of open government data around the world. The survey is designed to assess the openness of specific government datasets according to the Open Definition. Through this initiative we want to provide a civil society audit of how governments actually publish data - with input and review from citizens and organisations around the world. 


Open Knowledge International is a member of Open Data for Development (OD4D), a global network of leaders in the open data community, working together to develop open data solutions around the world. In edition to supporting the work we do on the Global Open Data Index and School of Data, through OD4D we provide direct support to civil society organisations and journalists to be able use data and technology effectively in their work. 

Mor, there is no need to have AODC, that can be covered through OD4D

**Comment by emmabeer** [comment]
**OpenTrials** aims to locate, match, and share all publicly accessible data and documents, on all trials conducted, on all medicines and other treatments, globally.

**Comment by vdtree** [comment]
As the use of content mining is significantly lower in Europe than in some countries in the Americas and Asia, the FutureTDM project seeks to improve uptake of text and data mining (TDM) in the EU. FutureTDM actively engages with stakeholders such as researchers, developers, publishers and SMEs and looks in depth at the TDM landscape in the EU to help pinpoint why uptake is lower, to raise awareness of TDM and to develop solutions.

**Comment by mtrpires** [comment]
School of Data is a network of creative and sharp-minded data-literacy trainers, spreading data love all around the world. They do that through our Global Fellowship Programme and Member Organisations, who provide journalists and civil society groups with the skills and tools they need to maximise the impact of their work through evidence-based approaches.
