### ISSUE TITLE
Add in the field 'link to forum group' on the group page on the site.

### ISSUE THREAD

**Issue by morchickit** [okfn/website#299]
Currently we have a mailing list address, but not forum link. Still some groups still keep both, it will be good to add this field so both can be presented.

**Comment by morchickit** [comment]
Forum example - https://discuss.okfn.org/c/local-groups/okbr

**Comment by yotammanor** [comment]
A somewhat related question:

The links on the sidebar suppose to have a link next to them, like this:

![image](https://cloud.githubusercontent.com/assets/5147457/20605844/0f1f0548-b276-11e6-8cea-1a858775d3f8.png)

It currently does not load the library that shows the icons, so it looks now like this:
![image](https://cloud.githubusercontent.com/assets/5147457/20605884/44bd0772-b276-11e6-8be7-e254999ee3e8.png)


The questions are:
1. Should I fix this?
2. If so, what icon should I use for the forum?

@morchickit

**Comment by morchickit** [comment]
We should fix it! However, there is no icon for the forum. I think we use a
speech bubble last time
