### ISSUE TITLE
People profile on groups pages show an email icon, even though the is no email address email for that person

### ISSUE THREAD

**Issue by morchickit** [okfn/website#300]
See example here of Asmen Gul in the OK Sweden page 
![screen shot 2016-06-22 at 15 39 08](https://cloud.githubusercontent.com/assets/3273659/16270803/884f5db6-388f-11e6-8d36-18c0e49fe82c.png)

**Comment by k-nut** [comment]
It seems like we just don't check. Changing the [line in question](https://github.com/okfn/website/blob/master/foundation/organisation/templates/organisation/member.html#L20) to `{% if not skip_email and person.email %}` should be sufficient for this.

**Comment by k-nut** [comment]
Just pushed a small fix for this on #301

**Comment by k-nut** [comment]
Closing this as it is part of the new design and proper handling was introduced in commit 38645c4.
