### ISSUE TITLE
Remove the following fields from the local groups category in the CRM

### ISSUE THREAD

**Issue by morchickit** [okfn/website#304]
- Google + page
- Youtube page
- Wiki page

Not one single group use these.

Thanks!

**Comment by k-nut** [comment]
[Spain](https://okfn.org/network/spain/) actually does use youtube. You are right though that no other groups uses any of the three mentioned. Should we risk a Spanish riot? 😉

**Comment by k-nut** [comment]
Done in #305

**Comment by morchickit** [comment]
Oh, I think they will forgive us. :-)
