### ISSUE TITLE
Network page broken on staging

### ISSUE THREAD

**Issue by k-nut** [okfn/website#306]
The pages on staging below `/network/` currently return a 500. Unfortunately it is not possible to debug this as Djangos default behavior is to send an email to the admins but sending emails is configured to use mandrill which does not work anymore. An alternative for this is needed so that it can be fixed.

Error message:
```
compressor.exceptions:OfflineGenerationError: You have offline compression enabled but key "05235a73d6eb8c31b050d50307e22ce8" is missing from offline manifest. You may need to run "python manage.py compress".
```

And running `python manage.py compress` unfortunately seem to not solve the issue...

Possibly helpful resources:
- https://github.com/django-compressor/django-compressor/issues/169
- https://chriskief.com/2013/09/18/django-compressor-offlinegenerationerror-and-500-html-handler500/

**Comment by pwalsh** [comment]
You can change the debug messages to go to STDOUT.

**Comment by k-nut** [comment]
Yep. I also discovered that. And I can also check Newrelic. Unfortunately it is still unclear to me where that error comes from but I will continue investigating.

**Comment by k-nut** [comment]
Doing some rolling back it seems to be broken since this commit:  https://github.com/okfn/website/compare/70618a7...50fa466

**Comment by k-nut** [comment]
Fixed by https://github.com/okfn/website/pull/303/commits/7cb5bfbbdf3ddc8608fb387fa52a92e488f6d3ba Now we just need to find another way to keep the javascript from running if there is a custom sidebar and not the navigation
