### ISSUE TITLE
Replace the email address for people who has the address remove@ on the website

### ISSUE THREAD

**Issue by morchickit** [okfn/website#307]
Some people entities has this address and we need to replace it

**Comment by k-nut** [comment]
What do we want to replace it with? I'm wondering if this was supposed to mean that the users should be removed entirely?

**Comment by morchickit** [comment]
I guess, from my prior experience, that some of them need to removed, and in some of them we just need to update it to their new email.

**Comment by morchickit** [comment]
Done.
