### ISSUE TITLE
Change handling of gravatar

### ISSUE THREAD

**Issue by k-nut** [okfn/website#311]
I'll summarize our plan as follows:
- Remove the hover to change image feature, only use one image per person
- Use only gravatar for the team
- Use hardcoded pictures for everyone else (board, network, etc)

Can you confirm that is correct @morchickit ?

This is also still awaiting changes from @smth about aspect ratio of images. Assigning him to this until it is figured out.

**Comment by smth** [comment]
Any image will work now, just needs to be configured like so https://github.com/okfn/website-mockups/blob/master/templates/board.html#L23-L24
