### ISSUE TITLE
When hovering on Forum icon the text shows "source-code"

### ISSUE THREAD

**Issue by morchickit** [okfn/website#314]
Also, text is not a hyperlink, and it should be

![screen shot 2016-07-08 at 10 48 27](https://cloud.githubusercontent.com/assets/3273659/16683837/ae6d03d8-44f9-11e6-9093-0f75c3627b90.png)

See frictionless data example

**Comment by k-nut** [comment]
@morchickit this is fixed and deployed to production now.
