### ISSUE TITLE
Expand width of dropdown menus

### ISSUE THREAD

**Issue by nibecker** [okfn/website#315]
Dropdown menus are to narrow so that e.g. "mission and what we do" breaks 2x … Same for "current projects"

![image](https://cloud.githubusercontent.com/assets/17476188/16684042/1846798e-4503-11e6-859c-368c4839531f.png)

**Comment by k-nut** [comment]
@smth we could just set the width of those `ul`s to `200px`? What do you think?

```
.site-header nav .primary>li.has-children:hover>ul {
    display: block;
    width: 200px;
}
```

Here's a screenshot of how that would look:

![screen shot 2016-07-11 at 10 17 48](https://cloud.githubusercontent.com/assets/1096357/16724015/c4236dc6-4750-11e6-860e-94105cd9b07a.png)

**Comment by smth** [comment]
Yeah, I think that'll be fine @k-nut

**Comment by k-nut** [comment]
@morchickit: fixed and deployed to production 🚀
