### ISSUE TITLE
Make icons order consisted in project page

### ISSUE THREAD

**Issue by morchickit** [okfn/website#316]
Currently, the order is random as this picture shows:
![screen shot 2016-07-11 at 10 56 58](https://cloud.githubusercontent.com/assets/3273659/16726865/5d96f0c2-4756-11e6-8265-c3bca3dc9caf.png)

Make homepage first, source code second, forum third, twitter fourth.

**Comment by k-nut** [comment]
The order was always the same but not as wanted. 39e39a2 changes the order to be as desired.
