### ISSUE TITLE
Mission copy clipped when browser window is medium width

### ISSUE THREAD

**Issue by brew** [okfn/website#319]
The bottom of the mission copy is clipped and missing when the browser window is between wide and narrow (about 1150px). See screenshot:

<img width="1105" alt="okfn_org_mission" src="https://cloud.githubusercontent.com/assets/3993/16870882/cabd48cc-4a7b-11e6-9c65-83bb85245250.png">

**Comment by k-nut** [comment]
I think the text in the original design by @smth was much shorter. Here we are still using the old one. Maybe @morchickit can just change it in the cms?

**Comment by morchickit** [comment]
And fixed!
