### ISSUE TITLE
twitter&facebook links in blog header point to hompages, not OK accounts

### ISSUE THREAD

**Issue by mlinksva** [okfn/website#321]
True for http://blog.okfn.org/ and http://planet.okfn.org/

**Comment by gocemitevski** [comment]
@mlinksva: updated the links on `blog` and `planet` and they now show correct URLs. Editing of these values is also possible from the WordPress Admin at `[website-address]/wp-admin/themes.php?page=theme-options`.

I will also check any other site that uses the new theme.

**Comment by gocemitevski** [comment]
@mlinksva this is an issue on any site that uses the new theme. The previous values from the old theme are either not recognized or not existent.

I will update the theme so these values are initially set correctly, by default.

**Comment by gocemitevski** [comment]
@mlinksva this has been resolved. The new WordPress theme now loads the default values if none has been specified.
