### ISSUE TITLE
Project descriptions on https://okfn.org/projects/old cutting off after 100 characters

### ISSUE THREAD

**Issue by StephenAbbott** [okfn/website#322]
Screengrab: 
![screencapture-okfn-org-projects-old-1468933485481](https://cloud.githubusercontent.com/assets/1506468/16950776/2a899d70-4dc2-11e6-8767-a16391284467.png)

**Comment by StephenAbbott** [comment]
Full descriptions look fine on the current projects page at https://okfn.org/projects

**Comment by morchickit** [comment]
Make project description 250 characters

**Comment by yotammanor** [comment]
@StephenAbbott 
 It was already changed a while ago to a max_length of 400 characters. But the teaser text does not update automatically, someone has to rewrite the teasers manually.

Of course, I can also write a script that generates a teaser automatically, but that's a different requirement.

CC: @morchickit

**Comment by morchickit** [comment]
I will leave that to decision of the comms person. @sierra4 , what do you say?

**Comment by sierra4** [comment]
@morchickit @yotammanor just so i understand correctly - the text for old projects can be 400 characters but doesn't yet have the added text yet. so each old project text just needs to be updated in django? happy to update this if that is the case. i assume this also means that the text limit shouldn't be a problem for when current projects are moved to old projects?

can we get a content tag going and add it to this and remove the bug tag (i don't have permission for tags).

**Comment by yotammanor** [comment]
@sierra4 you got it right, the text is editable in the CMS Admin interface.
Also, changing a project from current to old is just a checkbox you can switch on and off, any other property (e.g. teaser or description) should not be affected.

I started with removing the `bug` label, but I can't add a `content` one instead.

**Comment by smth** [comment]
This reads as though the fix here should be to "Edit page" then re-save or re-enter the contents. However, the admin for this page appears to be one empty static placeholder (for me at least).

**Comment by serahrono** [comment]
@smth I had a look, the solution here is to update teaser text for all old projects from the CMS, as the 100 character limit has been lifted. Project Teaser and Project Description text are two different entries, so worth taking a note of that. 

I have now chatted to @liekeploeger about it and assigning this issue to her.
