### ISSUE TITLE
Staff statuses should be in a consistent order

### ISSUE THREAD

**Issue by smth** [okfn/website#323]
Looks to me like the active/recent status is being moved to the first position.

**Comment by k-nut** [comment]
True, I wanted to make sure that the most recently updated one was always selected by default. Therefore I introduced the [`nowdoing_with_latest`](https://github.com/okfn/website/blob/master/foundation/organisation/models.py#L36) property which marks the most recently updated entry but also sorts the entries as a side effect.

It should only be necessary to sort the entries by something else after the marking of the newest one to achieve a consistent layout.

[usage in template](https://github.com/okfn/website/blob/master/foundation/organisation/templates/organisation/member.html#L60)

**Comment by yotammanor** [comment]
@smth what should it be ordered by, then?
And should the default selection always be the first (leftmost) element, according to the decided-upon order? Or should it be the latest? Or something else?

**Comment by sierra4** [comment]
@yotammanor
standard order for status:
left to right: email, twitter (if they have one), homepage (if they have one), and then ordered with latest updates following those three 'fixed' ones.

**Comment by yotammanor** [comment]
@sierra4 and which of those should be selected by default?

**Comment by yotammanor** [comment]
@sierra4 I've currently put the first element (i.e. `email`) as the default active one, let me know if you want some other option.

**Comment by sierra4** [comment]
@yotammanor sorry default should be email, twitter and homepage (if they have the latter ones)

**Comment by smth** [comment]
@sierra4 @yotammanor this is pretty much the opposite of what I had in mind when I opened this. The order was not the issue here, so much as the consistency. Currently new statuses get put at the start of the list; my intention was that the order remained constant. See for example [here](https://cloud.githubusercontent.com/assets/1375708/16048314/7b89752a-324b-11e6-8333-36638a6de48b.jpg), reading is always second, even when it is the most recently updated (and so active). I'm open to discussing this though.

**Comment by sierra4** [comment]
@smth Sorry for confusion, Sam! Agree consistency is the primary issue. was looking to impose order for consistency's sake but don't really know what default means here.

So @yotammanor ignore previous - for consistency can we go with the following order:

Working on, Location, Reading, Listening, Watching, Eating, Twitter, Homepage, Email

this order would always stay the same, regardless of latest update.

feel free to change if I've still missed the point, Sam...

**Comment by yotammanor** [comment]
@smth @sierra4 - The thin is that not everyone has a "Status" type info filled, so it won't look consistent if they are put first. 

On the other hand, Email is required, so it is a good option for a leftmost (and active by default) option. Other fields are optional, so what I would've done is check to which are the most used fields, and set a (constant, consistent) order according to this.

But if you want me to do it: 
> Working on, Location, Reading, Listening, Watching, Eating, Twitter, Homepage, Email

then of course this is not a problem.

**Comment by smth** [comment]
Yeah, go with that order.

**Comment by yotammanor** [comment]
@smth which should be the default active selection?

**Comment by smth** [comment]
If the person has updated a status, then the most recent status should be active. If not, make email the active item.

**Comment by sierra4** [comment]
QA check - statuses are in consistent order
