### ISSUE TITLE
Unnecessary overriding of margin on homepage h2

### ISSUE THREAD

**Issue by smth** [okfn/website#324]
There is an inline style on the banner heading (probably relating to https://github.com/okfn/website/issues/319), resulting in incorrect text alignment.

![banner-padding](https://cloud.githubusercontent.com/assets/1375708/17360507/e4a897ea-5963-11e6-89ba-05e9d81f2ea2.jpg)
Left: Correct, without inline `margin-top: 0;`.
Right: Current.

**Comment by yotammanor** [comment]
@smth this extra styling is added automatically by the CMS element (a Text Blurb, with heading 2).
It can be edited through the admin, by finding the text element -> edit -> edit  -> source -> remove the style attribute.

@morchickit I can do it myself if you give me admin permissions on the actual website, or have someone with permissions do it.

**Comment by yotammanor** [comment]
@morchickit now that I have permissions - is this the sort of thing you want me to do (change things in the CMS frontend)? Or is someone else in charge of this kind of tasks?

**Comment by morchickit** [comment]
@sierra4, want to give this a try and do it instead of @yotammanor ?

**Comment by morchickit** [comment]
Cool. Changed.

**Comment by sierra4** [comment]
QA check - margin styling removed and text alignment correct, but can @smth confirm that this is now okay?

looks to me like there is more black space above the text in the 'correct' example above than currently on the homepage but not sure if this is something that can be fixed with more styling.

**Comment by smth** [comment]
Looks good to me.
