### ISSUE TITLE
Search does not work on the site properly 

### ISSUE THREAD

**Issue by morchickit** [okfn/website#326]
- On Chrome, when trying to click on the search icon, nothing happens.
- On Safari, when clicking on the search icon it is working, but does not look good with the upper toolbar (see image)
  ![screen shot 2016-08-08 at 16 42 37](https://cloud.githubusercontent.com/assets/3273659/17486112/83eec1b8-5d87-11e6-9acc-cab236c1e31b.png)

**Comment by pwalsh** [comment]
@morchickit did you do QA on this on the last iteration, or is this some new bug somehow?

**Comment by morchickit** [comment]
TBH, I think we missed it in the last iteration (meaning that we didn't do QA on this).  The slack chat shows that it worked on staging, but I can't see any evidence that we checked it when the site was live.

**Comment by smth** [comment]
[This](https://github.com/okfn/website/blob/c551bf91fefa50806dadab4699595ee8b13235cb/static/scss/_header.scss#L65) will be what's causing the display error. I don't think that was in my original code, but I'm sure it was added for a reason.

**Comment by k-nut** [comment]
Looks like that was introduced here https://github.com/okfn/website/commit/6aa4ad3a9d365482045c4a4a1b7fd6b896a4e8f8 in the hope to fix this: https://github.com/okfn/website/issues/317

**Comment by smth** [comment]
OK, so the`z-index` of the search bar and logo need to be increased too.

**Comment by yotammanor** [comment]
@morchickit is this the way it's supposed to be:
![image](https://cloud.githubusercontent.com/assets/5147457/20136035/971a4766-a67b-11e6-81be-f2a9d7e523ec.png)

Or should the logo stay visible? Or any other requirement?

**Comment by morchickit** [comment]
I think this is the right way. @smth please confirm.

**Comment by smth** [comment]
Logo should stay visible (so its z-index probably also needs increasing).

**Comment by smth** [comment]
I see that this has been closed. Is this fixed but just not pushed live? (It seems we still have the problem of the menu appearing in front of the search bar).

**Comment by yotammanor** [comment]
@smth yes, that's the issue.
@morchickit maybe we do need some sort of a "pending deployment" label/list.

**Comment by sierra4** [comment]
QA check looks good - search bar appears 'over' the menu and logo is visible.
