### ISSUE TITLE
URLs missing from home page carousel

### ISSUE THREAD

**Issue by smth** [okfn/website#328]
While @morchickit reports that there are URLs present in the CMS, there are no corresponding `href`s present on the site. They should be added to the `a.carousel-caption` (if set in the CMS).

**Comment by yotammanor** [comment]
Okay, found the source.
In https://github.com/okfn/website/blob/master/foundation/features/templates/feature_plugin.html#L15
the URL is on attribute feature.link, instead of feature.url

Changed it locally and it works. Will PR right away.
