### ISSUE TITLE
Missing Open Graph tags

### ISSUE THREAD

**Issue by smth** [okfn/website#330]
We seem to be missing an `go:image` at least. Facebook is showing a white logo on a white background.

**Comment by yotammanor** [comment]
Hi @smth and @morchickit 

Can you please be more descriptive of the required feature?
Do you want me to make every page on the website optimized for facebook sharing? Just the homepage? What should a shared page look like?

**Comment by yotammanor** [comment]
@smth the reason fb shows a white logo is because the image used on the website is indeed white (with the green background color added in css).

So in order to solve this, I'll need a link to an image asset of the logo with the background embedded (the current image is at a.okfn.org). Do you know where I can find an image like that?

Also, I need to edit the link's description. I think it should be the following paragraph:

> A WORLD WHERE KNOWLEDGE CREATES POWER FOR THE MANY, NOT THE FEW.
THIS IS THE WORLD WE CHOOSE.

Does that make sense?

cc @morchickit

**Comment by yotammanor** [comment]
Once the code for this task is deployed, manually initiate a Facebook Scraping of the website, through here: https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Fokfn.org%2F

**Comment by smth** [comment]
Yeah, your suggestion is what I was implying here @yotammanor. I don't think we currently have a suitable image to use, one needs to be created (probably by me). In the short term, I guess this image would be an improvement https://a.okfn.org/img/oki/standard-rgb-667x687.png

**Comment by yotammanor** [comment]
Cool. I'll use that.
Once there's a new image let me know, and keep in mind that this image
should have a new URL, or FB won't replace the cached version. Thought it's
worth mentioning.

Another question:
Assuming that the shared link is not the home page. How does that affect
the texts and images? Or should I focus on the homepage and leave the other
pages for another time (and/or another github issue)?

**Comment by smth** [comment]
Assuming that there are no OG tags on other pages already, I think this image one should be used for all pages for now.

**Comment by yotammanor** [comment]
@smth And what about the text? Should it also be that OKI tagline for all pages?

**Comment by smth** [comment]
There are a few text based tags, I guess you are referring to `description`. I have no strong feelings about this personally. The image is the only thing I recall looking broken at the time of making this issue. Perhaps raise this with the comms team.

**Comment by yotammanor** [comment]
![image](https://cloud.githubusercontent.com/assets/5147457/20342848/be8f84ea-abf4-11e6-9529-be64ff6b1f5c.png)

**Comment by yotammanor** [comment]
I'm using this image: https://a.okfn.org/img/oki/standard-rgb-334x344.png

There's a margin problem. Is there another version that leaves more margin around the image? around the same size?

@morchickit @smth

**Comment by morchickit** [comment]
I see that the margin problem is in all of them, but maybe using the small
version and not the standard will help?

**Comment by yotammanor** [comment]
@morchickit the small one is too small, there's a 200*200 minimum.

**Comment by smth** [comment]
I just made a quick image. Try this:
![share](https://cloud.githubusercontent.com/assets/1375708/20356026/412770b8-ac1b-11e6-9a10-ff0edc1f5e50.png)

**Comment by yotammanor** [comment]
![image](https://cloud.githubusercontent.com/assets/5147457/20404355/439dcbb0-ad0d-11e6-932c-a4ba063dee7e.png)

Working for us? 
@smth @morchickit

**Comment by morchickit** [comment]
perfect!

**Comment by morchickit** [comment]
@yotammanor the current open-graph one is still the old one. When can we close this?

**Comment by yotammanor** [comment]
@morchickit when we're done with November Sprint task, and staging deployment is stable, we can then deploy to production, and then we'll be done.

**Comment by morchickit** [comment]
@yotammanor - is this now done?

**Comment by yotammanor** [comment]
Yes

**Comment by sierra4** [comment]
QA check - image and text description coming through on facebook
