### ISSUE TITLE
Content: Broken link on /opendata/how-to-open-data/

### ISSUE THREAD

**Issue by danfowler** [okfn/website#332]
> The handbook introduces you to the legal, social and technical aspects of open data. It can be used by anyone but is especially useful for those working with government data. It discusses the why, what and how of open data — why to go open, what open is, and the how to do open. Read it online or **download a PDF**.

http://opendatahandbook.org/pdf/OpenDataHandbook.pdf

via @kemelzaidan

**Comment by morchickit** [comment]
Any specific location? I took similar text already, but I need a URL to page this is on.

**Comment by roll** [comment]
@morchickit 
https://okfn.org/opendata/how-to-open-data/

**Comment by morchickit** [comment]
Sorry, missed it. Basically it because we don't export the handbook to PDF anymore. I change it manually on the site.

**Comment by danfowler** [comment]
👍

**Comment by enyst** [comment]
This is still happening, in the last phrase on the page there is a broken link to a PDF..

**Comment by morchickit** [comment]
Removed.
