### ISSUE TITLE
Blogposts: Preview text not converting HTML on home page

### ISSUE THREAD

**Issue by smth** [okfn/website#333]
Some HTML should probably be converted here, such as `&#8217;` to a quotation mark / apostrophe.

**Comment by hazel28** [comment]
8217

**Comment by morchickit** [comment]
@yotammanor can you have a look at this please

**Comment by yotammanor** [comment]
@morchickit sure. Do you maybe have a real world example of a post that it's summary got confused?

**Comment by smth** [comment]
I guess if you includes more posts in your local version, you'll eventually find one with HTML characters in it. There was an example of this at the time I created the issue.
