### ISSUE TITLE
Installed Packages not mentioned in requirements

### ISSUE THREAD

**Issue by yotammanor** [okfn/website#335]
As I was installing the project locally, I installed from `requirements.dev.txt`.
After I was done, I got import errors that were solved once I installed:

- django-treebeard
- django-formtools (the latter was also missing from `INSTALLED_APPS`, but imported in the code)

Also, some of the installed packages require some unmentioned non-python libraries (libxml, libxslt, libsasl2, imaging libararies for PIL, etc.)

**Comment by morchickit** [comment]
This is actually need to be discussed with @pwalsh

**Comment by pwalsh** [comment]
no it doesn't. it is just the type of thing to fix - total no brainer :)
