### ISSUE TITLE
Group page doesn't present the group members correctly 

### ISSUE THREAD

**Issue by morchickit** [okfn/website#337]
The display seems broken 
![screen shot 2016-11-09 at 11 38 17](https://cloud.githubusercontent.com/assets/3273659/20140084/2b8bdac2-a681-11e6-9602-6ef7ba060559.png)

**Comment by yotammanor** [comment]
Hi @morchickit and @smth 

I was able to make it look like this:
![image](https://cloud.githubusercontent.com/assets/5147457/20175416/49108dde-a74b-11e6-9f35-adfc025758e7.png)

And on narrow screens, likes this:
![image](https://cloud.githubusercontent.com/assets/5147457/20175437/5b7f8e3e-a74b-11e6-9ffb-981a5716de8d.png)


Is this what you were looking for?

**Comment by morchickit** [comment]
yes, perfect!

**Comment by yotammanor** [comment]
The changes I made introduced another display issue. I'm fixing it now.
