### ISSUE TITLE
A link to a Working group within a Chapter page is directing to the wrong place

### ISSUE THREAD

**Issue by yotammanor** [okfn/website#338]
See for example [here](https://okfn.org/network/austria/).
The link to "Open Science" directs to the page of the chapter (where the user is at the moment)

**Comment by morchickit** [comment]
That's not a bug, that's actually because we don't show these groups types
(working group) anywhere on the website. I think we used to do it a
LOOOOONG time ago though.

**Comment by morchickit** [comment]
I removed it from the Austria group, but we might want to remove this element  - Networkgroup-workinggroup relationships From the network group attributes.
