### ISSUE TITLE
local development environment uses a different jQuery version then production

### ISSUE THREAD

**Issue by yotammanor** [okfn/website#345]
In production: v2.2.4
In development: v3.1.1

This affects the fact that on development there's an error loading the menu (the error is fixed by downgrading. The error description and possible causes is described on SO, [here](http://stackoverflow.com/questions/37738732/jquery-3-0-url-indexof-error))

**Comment by morchickit** [comment]
OK, just to understand it - we need to downgrade the development? Why can we just upgrade the production?

**Comment by yotammanor** [comment]
First, this is an FYI assignment, like the other one, so I won't do that again.

But to answer your question, the upgrade created problems (menus are not loaded correctly, you can see it in the staging website now). I guess that what we want to do is to both upgrade and solve this problem, this will take longer though.

**Comment by yotammanor** [comment]
Okay, as discussed above, the real issue is some code incompatibility with jQuery >=3.0.0. I'm closing this one and open a new issue.
