### ISSUE TITLE
Add subscribe button to header

### ISSUE THREAD

**Issue by sierra4** [okfn/website#347]
Alongside Facebook Twitter and Donate buttons can we get a Subscribe button with an email icon in top right of header?

The Subscribe button should link to this sign-up page: http://okfn.us9.list-manage2.com/subscribe?u=73f922f8e68e21a10efa21f02&id=32d370a7fc

**Comment by yotammanor** [comment]
@sierra4 @morchickit @smth 
Pick an icon :)

(list of icons available [here](https://github.com/Keyamoon/IcoMoon-Free/blob/master/IcoMoon-Free.psd)

**Comment by smth** [comment]
You are not restricted to Icomoon icons when using Icomoon. I suggest the Entypo `mail` (envelope) icon. I think that will be in-keeping with the other icons there.

(If you need assistance adding to the icon font, let me know)

**Comment by yotammanor** [comment]
@smth yes I'd love your assistance adding the `@font-face`.
I've never done this before and I ran into a block that I expect to pass much faster with your help :)

**Comment by morchickit** [comment]
@smth was on summit with us, so he can help next week.

**Comment by yotammanor** [comment]
Then I'm blocked with this task till next week :)

**Comment by smth** [comment]
This is now hopefully unblocked :)

**Comment by yotammanor** [comment]
So far so good :)
Thanks!

**Comment by sierra4** [comment]
QA check - button in position and works
