### ISSUE TITLE
Add Scotland flag to the country flag of the local groups

### ISSUE THREAD

**Issue by morchickit** [okfn/website#371]
Currently Scotland's flag is the UK flag :-( @yotammanor can you have a look to estimate how difficult it is?)

**Comment by yotammanor** [comment]
Well, I can't find a Scotland flag at all, so I guess it was manually set to the UK's flag.
I'm trying to see if an updated version of the flags icon packages includes a Scotland flag as well.

**Comment by yotammanor** [comment]
https://en.wikipedia.org/wiki/ISO_3166-1 - Scoltand is not listed there, and we're using this list.
I can add a custom Country of my choice, assign it a country code and add the flag. I'd say 1-2 hours.
@morchickit should I do that?
