### ISSUE TITLE
Set-public-status feature not working on website.

### ISSUE THREAD

**Issue by sierra4** [okfn/website#381]
Relatablebot isn't responding to additions to the #set-public-status channel in slack and these changes are not being added to website as of Mon 13 Feb.

**Comment by danfowler** [comment]
Hi @sierra4 #relatable bot is working now.   I've also pushed it to a new repo under the /okfn/ organization.  Issues related to it can be raised there in the future:

https://github.com/okfn/relatable-chatbot/issues
