### ISSUE TITLE
Storage space needed for blog.okfn.org

### ISSUE THREAD

**Issue by sierra4** [okfn/website#382]
![screen shot 2017-02-16 at 15 12 02](https://cloud.githubusercontent.com/assets/21339389/23027307/c6e33a06-f45b-11e6-8009-a85e511999d5.png)
![screen shot 2017-02-16 at 15 10 42](https://cloud.githubusercontent.com/assets/21339389/23027306/c6c834cc-f45b-11e6-83d3-07f500e0507d.png)

Hello - can you please add storage to blog.okfn.org We cannot add media to the blog until further storage space is added.

Dashboard says 600 MB space allowed - 600.25 MB space used

**Comment by gocemitevski** [comment]
@sierra4 the issue is now resolved.
