### ISSUE TITLE
Website menu restucturing

### ISSUE THREAD

**Issue by liekeploeger** [okfn/website#390]
Hi Paul, we have completed the menu restructuring of the OKFN page, but need your help with two final things: 

Change menu title ‘Current projects’ to ‘Current work’
Change menu title ‘Old projects’ to ‘Past work’

And move these two menu items to the top of the sub menu, to show:

WHAT WE DO
Current work
Project participation guidelines
Blog
Past work

**Comment by jobarratt** [comment]
This card was written before the latest round of work on the website which included the addition of the  services section of the site. I Personally think the way things are set up on the staging site is perfect. Projects are definitely distinct from services, and the division into 'old' and 'current' is very clear to me. 

The credentials are designed as a way to show 'what we do' and these may or may not be tied to a current project. But they don't need to be. 

The projects page could perhaps do with expanding, but i think for now it does a functional job.

**Comment by smth** [comment]
In terms of adding the Services section (prominently), based on the current structure, I think we need to add it and "Projects" as top level items, rather than nested under "What we do". Secondarily, the complimentary items - "Who we are" and "What is open?" could be moved to "About", in order to free up space. This is the way things are set up on the staging site.

**Comment by sandervdwaal** [comment]
The new menu structure agreed between @liekeploeger and @sandervdwaal is defined here: 

https://docs.google.com/spreadsheets/d/1_6Yamb4U7HThsdX76xQEGRltGZsXt3wvnrQHC-8F8Os/edit#gid=1191475351

**Comment by smth** [comment]
This is more or less implemented now. There is some reordering that hasn't been done, it's a bit mysterious how some of this stuff is defined within the CMS. @liekeploeger feel free to go in and tweak stuff, you probably know more about how it works than me. Could you also check whether any changed URLs might cause broken links. I think only "Jobs" will have changed (if it wasn't at `/about/jobs` before).
