### ISSUE TITLE
Remove former OKI team members from Team page

### ISSUE THREAD

**Issue by StephenAbbott** [okfn/website#391]
Remove Freyja van den Boom, Dan Fowler and Georgiana Bere from OKI Team page https://okfn.org/team

**Comment by liekeploeger** [comment]
Hi Stephen, this has been done some time ago - in the future, you can also ask me on the Comms trello for these smaller type of edits :)

**Comment by StephenAbbott** [comment]
Thanks @liekeploeger. Will remember that in future

**Comment by pwalsh** [comment]
This tracker is for code issues, not content issues, which should go via the OKI comms team.
