### ISSUE TITLE
Certificate of https://espace.okfn.org/ expired

### ISSUE THREAD

**Issue by liekeploeger** [okfn/website#395]
The certificate of the site [https://espace.okfn.org/](url) (Open Content Exchange Platform) has expired. Could you update it?

This is a database we built for OpenGLAM; which is embedded on [https://openglam.org/documentation/](url) - because of the expired certificate the page currently does not display. Thanks!

**Comment by pwalsh** [comment]
@liekeploeger just saw this by accident. 

Moved to https://github.com/okfn/devops/issues/87
