### ISSUE TITLE
Page lov.okfn.org is down

### ISSUE THREAD

**Issue by liekeploeger** [okfn/website#397]
The page http://lov.okfn.org is down, see http://downforeveryoneorjustme.com/lov.okfn.org

**Comment by FlorianMittag** [comment]
The page http://lov.okfn.org/ is still down, yet https://dbpedia.org/ontology/ is linking to it via http://purl.org/vocommons/voaf#Vocabulary

At the moment, this is sadly just another example of outdated links in the world of Semantic Web and Linked Data

**Comment by amercader** [comment]
Thanks for flagging this.

http://lov.okfn.org/ it's just a redirect to https://lov.linkeddata.es/dataset/lov/, which was not working due to a misconfiguration but it is now working as expected
