### ISSUE TITLE
OK festival sites are down

### ISSUE THREAD

**Issue by liekeploeger** [okfn/website#409]
We have a couple of websites on editions of Open Knowledge Festival, all ending in okfestival.org (for example [http://2014.okfestival.org](http://2014.okfestival.org) and [http://2018.okfestival.org](http://2018.okfestival.org))

They are currently down: I get a 403 cloudflare error. Could you check up and make sure they are back online? Thanks!

**Comment by ilchebedelovski** [comment]
@liekeploeger @pwalsh This is a certificate issue, the security status on CloudFlare for okfestival.org is `Certificate Timing Out`, we need to upgrade the certificate manually to solve this issue. For completing this step a new purchase needs to be completed on CloudFlare in the `Crypto` tab.

**Comment by sandervdwaal** [comment]
@pwalsh Can you please make this purchase or let us know who else can do this?

**Comment by brew** [comment]
@ilchebedelovski If I order the certificate on CloudFlare, is there any other configuration that needs doing, or is that it?

**Comment by brew** [comment]
@ilchebedelovski @liekeploeger I think this is fixed now. There was a problem with the certificate on CloudFlare, so I just turned Universal SSL on and off again to reissue the certificate, and it now shows as 'active'. 

@liekeploeger Can you check it works as expected your end, then close this issue.

**Comment by sandervdwaal** [comment]
This works now on https, but on http  I get the nginx welcome page http://2014.okfestival.org/ 
@ilchebedelovski can you please look at that?  
The 2012 version properly redirects to https

**Comment by brew** [comment]
http://2014.okfestival.org/ works okay for me. What browser/os are you using @sandervdwaal?

**Comment by sandervdwaal** [comment]
Sorry @brew a hard refresh made it appear as normal so was caching issue. This is resolved now, thanks all!
