### ISSUE TITLE
Simplify deployment

### ISSUE THREAD

**Issue by chris48s** [okfn/website#476]
Remaining questions:
- What is redis doing in prod? Do we need it? It seems we _are_ using it for something in prod (if I turn it off stuff breaks), but not staging (if I turn it off everything is fine).
- How does the search work in prod? Is it using ElasticSearch or Whoosh? If we're using ES, could we use Whoosh in prod?
- Can we get this down to 1 container, 1 DB and a storage bucket? ~If so, could we move to Heroku or DO PaaS instead of GKE?~

**Comment by chris48s** [comment]
Did a bit more research on this..

Easy one first: we don't have a `SEARCH_URL` set in prod or staging any more - its commented out in `production-secret.yaml` and `staging-secret.yaml` this means we're not using ElasticSearch in prod. We're already using Whoosh, so that makes that simple. If we wanted to move to a PaaS provider, there's no extra work needed there.

On the redis side, django-cms uses a cache by default, although I suspect redis is overkill given the kind of traffic this site processes (a few hundred hits per day). Options here are:

- Carry on using redis. If we move the site, accept we also need a redis instance for it (Heroku, DO, etc will happily sell us one)
- Turn cache off completely:
  ```
  CMS_PLUGIN_CACHE = False
  CMS_PAGE_CACHE = False
  ```
- Switch to a cache engine that doesn't need an external service. Options for that are:
  - `django.core.cache.backends.filebased.FileBasedCache` (uses disk space on the app container)
  - `django.core.cache.backends.locmem.LocMemCache` (uses memory on the app container)
  - `django.core.cache.backends.db.DatabaseCache` (uses a table on the DB server)
  That would mean we are still using some kind of cache, but we can get rid of redis.

We can review this, but at least the options are clear now.

**Comment by chris48s** [comment]
Related reading:
- https://docs.django-cms.org/en/latest/how_to/caching.html
- https://docs.djangoproject.com/en/2.2/topics/cache/

**Comment by chris48s** [comment]
Current plan:
- Deploy one app container on Google CloudRun
- Get rid of redis one way or another (see above)
- Move `/media` storage bucket from AWS to Google Cloud (I think blob storage protocol is compatible across both clouds)
- Continue using CloudSQL for DB

Once that is done, look at downtime on deploy. At the moment we are handing off to the new container before it is ready to serve traffic. Is this an error in our Dockerfile or our orchestration setup?

**Comment by avdata99** [comment]
Done:
 - `/media` moved to Google Cloud storage
 - Cloud run ready. Automatic scaling
 - We are using Redis for caching
