### ISSUE TITLE
Upgrade to Django 3.2

### ISSUE THREAD

**Issue by chris48s** [okfn/website#543]
Aside from our own codebase, there are a variety of plugins and packages we use that interface with django:

**django-cms**

https://pypi.org/project/django-cms

We've now merged the PR upgrading django-cms to 3.9.0 https://github.com/okfn/website/pull/568. This is the first Django 3.2-compatible release of django-cms. I suspect now that domino has fallen there will also be releases of the various django-cms ecosystem plugins to follow it declaring Django-CMS 3.9/Django 3.2 compatibility:

* https://pypi.org/project/djangocms-admin-style
* https://pypi.org/project/djangocms-file
* https://pypi.org/project/djangocms-link
* https://pypi.org/project/djangocms-picture
* https://pypi.org/project/djangocms-text-ckeditor

**psycopg2**

Until we can upgrade to django 3 we need to keep psycopg2 on 2.8.x
Once we upgrade to django 3 we can upgrade psycopg2
See https://github.com/okfn/website/pull/561#issuecomment-865860728

**other packages**

These packages already have a release explicitly declaring django 3.2 support:

* https://pypi.org/project/django-countries
  merged: https://github.com/okfn/website/pull/535
* https://pypi.org/project/django-compressor
  merged: https://github.com/okfn/website/pull/546
* https://pypi.org/project/django-formtools
  merged: https://github.com/okfn/website/pull/545
* https://pypi.org/project/django-redis
  merged: https://github.com/okfn/website/pull/555

There are some packages where there is recent activity on the repo around django 3.2 support but no release on PyPI yet. Review these once django-cms unblocks:

* https://pypi.org/project/django-haystack
* https://pypi.org/project/django-reversion
* https://pypi.org/project/django-sekizai
* https://pypi.org/project/django-treebeard (this one is tested up to `django==3.1` on their repo, but `django-cms==3.9.0` depends on it and will run on `django==3.2` so I suspect `django-treebeard==4.5.1` will be fine, but test it)

There are a variety of packages where I don't expect to see a release explicitly declaring compatibility with django 3.2 in the near future. I think we will just have to try them and see what happens:

* https://pypi.org/project/dj-database-url
* https://pypi.org/project/django-csp
* https://pypi.org/project/django-markdown-deux
* https://pypi.org/project/django-pagedown
* https://pypi.org/project/django-s3-folder-storage

These packages also have some other known issue we need to deal with:

* https://pypi.org/project/django-mptt
  https://github.com/okfn/website/issues/533

**Comment by avdata99** [comment]
Fixed with #635
