### ISSUE TITLE
Subdomain Takeover

### ISSUE THREAD

**Issue by JoeMilian** [okfn/website#575]
Hey,

I noticed you had an unclaimed GitHub page, I took it over so no attacker is able to use it.

The subdomain: https://opendatacommons.okfn.org/

I hope I have informed you enough, If there are any issues please don't hesitate to message me.

Kind regards,

Joe (https://twitter.com/JoeMilian1)

**Comment by amercader** [comment]
Thanks a lot for flagging this @JoeMilian! I believe we have fixed it now
