### ISSUE TITLE
Remove AWS dependencies

### ISSUE THREAD

**Issue by avdata99** [okfn/website#607]
`django-s3-folder-storage` is no longer maintained and we don't use `DJANGO_USE_AWS_STORAGE` anymore.
Related with #606 

Clean code

**Comment by lucpretti** [comment]
@pdelboca This is related to your question about AWS and Google. Can you please review and close this issue if not relevant anymore?

**Comment by avdata99** [comment]
@lucpretti this will be fixed with #891.
We can close this when we finish

**Comment by pdelboca** [comment]
After merging #891 there are no longer references to AWS in the Repository.

Closing.
