### ISSUE TITLE
Missing page: Attribution

### ISSUE THREAD

**Issue by lucpretti** [okfn/website#842]
A page listing all images and videos used on the website.

Link to previous version as a template:
to http://web.archive.org/web/20230525200834/https://okfn.org/attribution/

**Comment by lucpretti** [comment]
Once published, the link needs to be added to the footer (“Refer to our attributions page for attributions of other work on the site.”)

**Comment by aivuk** [comment]
Could you add the list of images/videos? I don't know about the licenses used in all of them (like the ones on the rolling gallery)

**Comment by lucpretti** [comment]
Never mind - leave this task to me. I'll work on it this week.
