### ISSUE TITLE
Network members pages

### ISSUE THREAD

**Issue by lucpretti** [okfn/website#844]
Links to chapters' pages are currently redirecting back to the Network page. 

You can see below the new desired layout, and also in [Figma](https://www.figma.com/file/z9cWbZ61Sk9FE8XYtpOqrP/okfn.org---Website-2023?type=design&node-id=0%3A1&t=z2xlNOcUzSaAyAvJ-1).

![Screenshot 2023-06-06 at 23 36 42](https://github.com/okfn/website/assets/8523847/220c9d3b-902f-4abd-8718-acb242eb0ad2)

**Comment by lucpretti** [comment]
@aivuk Would you please move the "More information" box to be displayed right below the team cards (and before the static content)?

**Comment by aivuk** [comment]
done!
