### ISSUE TITLE
Implement blurred circles as plugins backgrounds

### ISSUE THREAD

**Issue by lucpretti** [okfn/website#845]
Following the patterns on the homepage, please add a feature for inserting blurred circles as a background option for all full-width components.

Amazing if both sizes and colours are editable.

Colours: 

- 00D1FF 70%
- E077FF 80%
- E4FF36 80%
- ADFFED 80%

**Comment by lucpretti** [comment]
Edgar worked on this issue, but I don't know the current status.

His approach was adding the ability to assign a blurred circle as a background to selected plugins. Here's a list of plugins that would be nice to have this feature added to:

- [ ] Heading
- [ ] Page Header
- [ ] Section opening (in the future, not yet developed)
- [ ] Carousel
- [ ] Gallery
- [ ] Newsletter
- [ ] Text

**Comment by amercader** [comment]
Can you add a screenshot of what do you mean by this? ie the expected result

**Comment by lucpretti** [comment]
Here you go:

![Screenshot 2023-07-12 at 12 15 35](https://github.com/okfn/website/assets/8523847/498d6cf2-117a-4813-bd61-deb4fe0acbe4)
![Screenshot 2023-07-12 at 12 15 44](https://github.com/okfn/website/assets/8523847/dcfbc835-21ab-4dc6-9b65-a425f5d80e45)
![Screenshot 2023-07-12 at 12 15 53](https://github.com/okfn/website/assets/8523847/b79d719a-7587-4a72-ac8e-206f873b2fad)

I took these screenshots from the homepage developed by Kan: https://ishigami.github.io/okfn_front/
