### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by amercader** [okfn/website#883]
Now that we have an up to date version of the site let's clean up and remove everything we don't need.

- [x] Upgrade python requirements: Act on all dependabot PRs. Tests and manual checking should flag any issues
- [x] Uprade JS requirements. We don't have frontend tests for this so I'll let whoever does it decide on an case by case basis
- [x] Remove old not used CMS plugins (maybe everything not in `foundation/okfplugins`?)
  - [x] Check all in use plugins in the production database

**Comment by pdelboca** [comment]
Can we add a task to update to the latest Python version? Currently it will fail in Python >= 3.9 due to issues with `backports.zoneinfo`.

**Comment by pdelboca** [comment]
After our last merges this can be considered as completed.

There are still somethings to cleanup but the major work has been done.
