### ISSUE TITLE
Make minor changes to existing plugins

### ISSUE THREAD

**Issue by lucpretti** [okfn/website#892]
All these plugins are part of the group OKF v2:
---

- [ ] **Article Link**
    - [ ] Add on hover / on click states (search for "Article" [here](https://ishigami.github.io/okfn_front/components.html))
    - [ ] Make URL field non-mandatory

---

- [ ] **Banner**
    - [ ] Implement different colors for each variation (search for "Banner" [here](https://ishigami.github.io/okfn_front/components.html))
    - [ ] Enable markdown in the `Text` field
---

- [ ] **Carousel**
    - [ ] Display each image's Alt text after 1 sec mouse hover
---

- [ ] OKImage
    - [ ] When not `In column`, display the caption below the image, not inside 
    - [ ] Change the option text from `Show caption` to `Use caption instead of text`
    - [ ] Display Alt text after 1 sec mouse hover

---
- [ ] Grid Column
    - [ ] How to "skip" a column? Example: say I want to add 2 blocks using the 2 central columns in a grid of 4. Suggestion: Maybe make it work like `Pills Menu` that always has the same size starting from the center
---

- [ ] Feature Block
    - [ ] Add the small arrow to the "Learn more" button (gets activated when an URL is added)
    - [ ] `Yellow` and `Yellow background` currently have the same layout. Needs to recover `Yellow` as the original yellow squared box (search for "Content Grid" [here](https://ishigami.github.io/okfn_front/components.html))
    - [ ] Add option `Text white` to `Blue background`, `Yellow background`, `Purple background` and `Rounded corners`
    - [ ] Add on hover / on click states to `Blue background`, `Yellow background`, `Purple background` and `Rounded corners`
    - [ ] Change type name from `Yellow` to `Yellow Box`
    - [ ] Change variant name from `White` to `White Box`

---

- [ ] Footer
    - [ ] Replace link of `Request a quote` with `/contact`

---

- [ ] Full Banner
    - [ ] Add option `Text White` (including a white button)

---

- [ ] Gallery
    - [ ] Rename plugin to "Running Gallery"
    - [ ] Stop automatic scroll on mouse hover
    - [ ] Make it draggable
    - [ ] Display each image's Alt text after 1 sec mouse hover
    
---

- [ ] Heading
    - [ ] Enable markdown in the `Title` field

---

- [ ] List
    - [ ] Rename option from `XL` to `XL no title`

---

- [ ] Newsletter
    - [ ] Rename plugin to "Call-to-action"
    - [ ] Create field to add button link
    - [ ] Prefill the linked form with the email added by the user
    - [ ] For type `Small` - Make the heading editable
    - [ ] For type `Small` - Decrease text and image sizes, align elements (search for "Campaign > Small" [here](https://ishigami.github.io/okfn_front/components-2.html))

---

- [ ] Page Header
    - [ ] Rename field from `Second text` to `Highlight text`
    - [ ] For type `Image left / Text right` - Centralise
    - [ ] For type `Image left / Text right` - Add bottom margin (the element is too close to the next one)

---

- [ ] PillButton
    - [ ] For type `Arrow` - I can't see the arrow, please add (search for "Button > Arrow" [here](https://ishigami.github.io/okfn_front/components.html))

---

- [ ] Quote
    - [ ] Enable markdown in the `Text` field

---

- [ ] Spotlight
    - [ ] Display Alt text after 1 sec mouse hover

**Comment by amercader** [comment]
If necessary, split one of these tasks into its own issue
