### ISSUE TITLE
Create additional plugins for lists and stats

### ISSUE THREAD

**Issue by lucpretti** [okfn/website#895]
To be added to the group OKF v2:
---

- [ ] Content List (search for "list" [here](https://ishigami.github.io/okfn_front/components-2.html))
Obs: Instead of a new plugin, could be a new variation to the `Article Link` (#892)

![Screenshot 2023-07-10 at 12 05 35](https://github.com/okfn/website/assets/8523847/28f3e6c1-23fc-4a88-8ac8-83087dc786b2)

---

- [ ] Number stats (search for "number" [here](https://ishigami.github.io/okfn_front/components-2.html))
    - [ ] Grid 1
    - [ ] Grid 2
    - [ ] Grid 3
Obs: Instead of a new plugin, could be new variations to the `Feature Block`

![Screenshot 2023-07-10 at 12 08 05](https://github.com/okfn/website/assets/8523847/1663a795-726a-4ea9-b02c-a5afc78c71a6)

---

**Comment by amercader** [comment]
To the implementer, if we re-use "Article link" please move it to the new plugins folder

**Comment by pdelboca** [comment]
@lucpretti this one is ready to review in Staging! I have deployed it this morning.

**Comment by lucpretti** [comment]
It's working great, thank you!

My only piece of feedback would be an ask to remove the "Learn more" button when the URL field is empty. @shashigharti @pdelboca
