### ISSUE TITLE
Add Open Graph metadata for better social sharing

### ISSUE THREAD

**Issue by lucpretti** [okfn/website#901]
Is there a way to make it available on each page, so we are able to customise the content for each?

**Comment by amercader** [comment]
@lucpretti We have these added to all pages now:

```html
            <meta property="og:title" content="Tech Services"/>
            <meta property="og:type" content="website"/>
            <meta property="og:url"    content="https://okfn.org"/>
            <meta property="og:description"         content=""/>
            <meta property="og:image"                content="/assets/img/OKF-logo-white-background.png"/>

```

`url` needs to obviously be updated to the current url, and I imagine the description needs to be customizable per page as well (with maybe a default). Do you need any additional tags not in here? Does the image needs to be customizable

**Comment by lucpretti** [comment]
Thanks @amercader.

Yes, I'd like to be able to customise `og:description` and `og:image` for each page.

**Comment by lucpretti** [comment]
`og:image` attribute is working fine, thank you!

What about the `og:description`? Where can I edit it?

**Comment by shashigharti** [comment]
Hi @lucpretti, description can be updated from page edit window.

![page-edit](https://github.com/okfn/website/assets/5582809/0f40a662-cd84-46a6-b47a-9e5a28807179)

Meta Description
![page-metadatadescription](https://github.com/okfn/website/assets/5582809/88ef2502-ff79-443a-8906-6e4ff31e8095)

Thank you!

**Comment by lucpretti** [comment]
Oh, perfect. Thank you @shashigharti !
