### ISSUE TITLE
Make homepage editable with current plugins

### ISSUE THREAD

**Issue by lucpretti** [okfn/website#902]
As of now, the okfn.org homepage is half hardcoded, half editable via plugins. We need to make this page as customisable as others. Edgar told me he was almost ready to implement that - so could you please check the state of the code?

I'm ready to build the new content once you deploy it (as I assume the current hardcoded content will be lost).

**Comment by amercader** [comment]
It's important to distinguish between plugins (which might have customizable content) and editable content. That's the one that you edit directly by double-clicking while logged in:



https://github.com/okfn/website/assets/200230/5115fe39-4b9d-423b-9851-70b9eceb7a34

The latter is the preferred way of editing content that won't be replicated across the site (ie we don't need a plugin for it). I don't know the specifics on how to enable it but I assume it's just marking it with some special block in the templates.

**Comment by lucpretti** [comment]
Thanks for the clarification. As you see, I've been calling "plugin" any editable content element because the system calls them plugins as well:

![Screenshot 2023-07-12 at 12 01 14](https://github.com/okfn/website/assets/8523847/f4dc1893-9cf8-4106-9262-81eb0a17ca07)

But I get what you mean. 

Creating plugins for any editable piece of content was Edgar's approach. Maybe there are others. I trust you in finding the best and easiest solution.
