### ISSUE TITLE
Banner block is missing

### ISSUE THREAD

**Issue by pdelboca** [okfn/website#911]
The following commit https://github.com/okfn/website/commit/29bb392c905af642797786d4262c1ac025f29c64 deleted the `{% block pagebanner %}{% endblock %}` block from the `general.html` template.

Therefore, there is not display of Django `messages` in the web. (For example, when submiting a Contact Form). 

If enabled, it will render some content but without proper style

We should:
 - Decide what to do with the content (and delete it from the database if so)
 - Fix so we have a proper place to display Django `messages`

### Example 1:
![image](https://github.com/okfn/website/assets/6672339/08bc5d14-d2c8-4696-8547-ab58194ca117)

### Example 2:
![image](https://github.com/okfn/website/assets/6672339/5b1512f1-853b-4f04-ad7a-bdc6481c42ec)

**Comment by lucpretti** [comment]
As far as I understand, in the old layout the banner was the opening "section" of each page, right? In the current version, most pages are using the Page Header plugin.

Is it possible to use the available plugins in or as a replacement for the banner block? 

If not, do you need a design for the banner block (including the messages)?

**Comment by pdelboca** [comment]
@lucpretti you are right. Initially the banner was the opening "section" of each page. 

The problem is that the section has:
 - A banner block to display confirmation messages for actions in the system with the same style as our new Banner. (Good)
 - A place holder for "blurb" and "banner images" (Bad)

There is no separation of concern and it doesn't make any sense in the design to have both in the same component, you are tightly coupling two completely different elements.

So:
 - I'm gonna re-introduce the feature to allow us to display messages to the user.
 - I'm gonna remove the "opening section" from it. We should be consistent and use the new "Header Banner" component.
