### ISSUE TITLE
Repeated styles in Feature Block

### ISSUE THREAD

**Issue by lucpretti** [okfn/website#921]
This bug was flagged at #892, but I'm creating a separate issue as it became urgent with the last deploy to main.

The Featured Block plugin has two repeated styles: `Yellow` and `Yellow background` currently have the same layout. 

We need to recover `Yellow` as the original yellow squared box (see below and/or search for "Content Grid" [here](https://ishigami.github.io/okfn_front/components.html)) and keep `Yellow background` as it is.

<img width="352" alt="Screenshot 2023-07-18 at 15 43 52" src="https://github.com/okfn/website/assets/8523847/ff589902-6679-4673-b67e-a1d65e53ff17">

**Comment by amercader** [comment]
@lucpretti what are the boxes that are broken on okfn.org?

The "Latest updates" ones look the same to the "Content grid" ones to me:



![Image](https://github.com/okfn/website/assets/200230/6b69af78-313e-4e29-aaee-467ea0c4ae56)

**Comment by amercader** [comment]
Got you

@shashigharti can you take this one first instead of #895?

**Comment by shashigharti** [comment]
@amercader Sorry I missed this message and just saw it. I will check this one first.

**Comment by lucpretti** [comment]
@shashigharti @pdelboca This is working correctly on next. Ready to deploy.
