### ISSUE TITLE
Bug on OKimage plugin layout after deploy

### ISSUE THREAD

**Issue by lucpretti** [okfn/website#966]
One of the correct layouts for the OKImage plugin, when I want to use it to feature content, is the following (as is on the [homepage](https://okfn.org/en/)):

![Screenshot 2023-08-23 at 10 56 09](https://github.com/okfn/website/assets/8523847/c6f4de8d-a4e7-4893-8340-4b2581c2ee46)

But for some reason after the deployment it's been displayed like a normal picture. The text is now shown as a caption, and the tag field completely disappeared. This example is from the [Tech Services](https://okfn.org/en/our-services/tech-services/) page.

![Screenshot 2023-08-23 at 10 54 13](https://github.com/okfn/website/assets/8523847/606faf03-c248-41ab-a395-5f99675262fb)

I tried to put the plugin inside a Grid Column, but it didn't work. Interestingly, the plugin is still working on the Homepage, but I assume it's because the homepage layout renders differently.

We need to revert it asap, pls.

**Comment by shashigharti** [comment]
Hi 
[@Lucas Pretti](https://openknowledge.slack.com/team/U045HFSQJSH)
 for this [issue](https://github.com/okfn/website/issues/966#event-10167498166) I checked the previously added images and noticed that it required adding url. I added url in test image it worked as before.

![image](https://github.com/okfn/website/assets/5582809/1b0317eb-efb8-4b0f-98c8-6452649967d8)

**Comment by lucpretti** [comment]
Oh great. Thank you @shashigharti! There were URLs before. So the bug was that the latest changes deleted the URLs.

I'll test it again and confirm back here.

**Comment by lucpretti** [comment]
Hmm, I'm afraid it's not the problem... The images I reported have a URL properly set, take a look:

https://okfn.org/en/our-services/tech-services/

![Screenshot 2023-08-23 at 13 02 35](https://github.com/okfn/website/assets/8523847/2f5ce220-f32a-41be-932f-c6db0cc4a7d9)

**Comment by shashigharti** [comment]
Thanks. I will check in the tech-services page then. I tested in home page only.

**Comment by shashigharti** [comment]
@lucpretti  Can you please share the full view of the plugin settings page.Thanks again!

**Comment by lucpretti** [comment]
![Screenshot 2023-08-23 at 13 29 40](https://github.com/okfn/website/assets/8523847/67a37d5f-a150-4de8-860d-78a79d5d9e27)

![Screenshot 2023-08-23 at 13 29 48](https://github.com/okfn/website/assets/8523847/b6597e09-923b-4066-aefe-83ecd77c2183)

**Comment by shashigharti** [comment]
@lucpretti I looked into this new change and it is not a bug. But it was requested in this [issue](https://github.com/okfn/website/issues/892). 

The output before this change(deployment) looks like this:

in column
![incolumn](https://github.com/okfn/website/assets/5582809/728ede88-c7a7-4863-87e9-c9661406d994)

not in column
![notincolumn](https://github.com/okfn/website/assets/5582809/2bcf9ed8-4d9e-4cde-b4f8-26917b1a7912)


After the deployment:

in column
![incolumn](https://github.com/okfn/website/assets/5582809/728ede88-c7a7-4863-87e9-c9661406d994)

not in column
![notincolumn](https://github.com/okfn/website/assets/5582809/a32b02da-63d6-4645-80f1-9d2288d4116c)

**Comment by shashigharti** [comment]
Shall I restore it back?

**Comment by lucpretti** [comment]
Ohh you're right. I requested that without being aware of the wider impact.

Yes, please revert it back. Let's find another solution for having captions displayed
