### ISSUE TITLE
Board page: Redesign

### ISSUE THREAD

**Issue by nealbastek** [okfn/website#97]
copy from here: http://okfn.org/governance/meetings/

**Comment by morchickit** [comment]
This whole page - https://okfn.org/about/board/board-meeting-minutes/ Looks bad and it's really hard to navigate to the minutes. @smth do you think you can help in make the navigation in the board section easier? Currently it's all in the sidebar.

**Comment by smth** [comment]
I certainly think I could make improvements, though I wouldn't say this page is any less usable than the rest of the site. I suggest that if we are going to put some effort in here, we first identify any other pages that could share a layout with this one. That way we can potentially design for more use cases.

**Comment by morchickit** [comment]
is issue #253 answer that?

**Comment by smth** [comment]
Possibly, though we could probably still benefit from some kind of archive template, so the minutes landing page (and similar pages) can be navigated more easily.

**Comment by morchickit** [comment]
Cool, let's do it!

**Comment by smth** [comment]
I wonder if the sidebar menu would actually make sense, if the content was displayed beside it (loading the latest by default).
![okfn_01_minutes_01](https://cloud.githubusercontent.com/assets/1375708/15247419/fc19b6ae-190b-11e6-8465-356e8692b2bd.jpg)

**Comment by morchickit** [comment]
Oh, that's look great!
