### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by sapetti9** [okfn/website#989]
The link to the "Network Guidelines" in okfn.org/network does not go anywhere.

Either we link something there, or we delete the sentence "Here is the [Network Guidelines](http://okfn.org/network/network-guidelines) document, which explains in detail how the Network works and the process for becoming a member."

Same goes for the icon just below:
<img width="827" alt="Schermata 2023-09-22 alle 17 43 46" src="https://github.com/okfn/website/assets/74717970/5f6ab971-b211-4c88-a76c-bc192e8b1cb8">

@lucpretti

**Comment by lucpretti** [comment]
Fixed!

It happened because of the new translations feature #898 that added `/en/` to all URLs.

Thanks for reporting @sapetti9 because it's worth it to review all links in texts and featured content – I'll do it right now.
