### ISSUE TITLE
Implement language switch button in the menu

### ISSUE THREAD

**Issue by lucpretti** [okfn/website#995]
The site is now entirely translated into Spanish, so we are good to go with the language switch button. (please refer to #898 for context).

As far as I know, the button is already implemented but not active (TBC). Anyway, here's the desired layout:

Normal state:
![Screenshot 2023-10-30 at 17 14 59](https://github.com/okfn/website/assets/8523847/924509d1-cf94-4255-9862-4268d3aa1361)

Hover state:
![Screenshot 2023-10-30 at 17 15 29](https://github.com/okfn/website/assets/8523847/3f347ff6-96da-47a3-82ab-5d0f0fc5228a)

Let me know what else you need from me.

**Comment by pdelboca** [comment]
Implemented in #1002
